demo:
  load: DEMO
  module: fixgw.plugins.demo
  initialization_file: "{CONFIG}/init_data/engines/forDemo.ini"

  tick_rate_hz: 10 # if engine_sim is enabled then output data at this rate
  segment_steps: 20 # number of steps per script segment for simulating transitions

  engine_sim:
    enabled: false

    full_sweep: true # if true, ramp egt(n)/cht(n)/bartest(n) from min to max for the given period
    full_sweep_period: 15 # secs

    rpm_mean: 2400
    rpm_amp: 200
    rpm_period: 45

    map_base: 18.0
    map_amp: 6.0
    map_period: 45.0
    map_rpm_coeff: 0.004

    oilp_base: 55.0
    oilp_amp: 8.0
    oilp_period: 50.0
    oilp_rpm_coeff: 0.003

    fuelf_base: 7.5
    fuelf_amp: 1.5
    fuelf_period: 60.0
    fuelf_rpm_coeff: 0.0015

    oilt_base: 85.0
    oilt_rpm_coeff: 0.01
    oilt_sin_amp: 5.0
    oilt_sin_period: 180.0
    oilt_alpha: 0.02

    # egt and cht settingsbelow only used if full_sweep=false
    egt_amp: 50
    egt_base: 650.0
    egt_amp: 40.0
    egt_period: 30.0

    cht_amp: 25
    cht_base: 200.0
    cht_amp: 20.0
    cht_period: 120.0
    cht_oilt_coeff: 0.05
    cht_alpha: 0.02

  fuel_drain:
    enabled: false

    tanks: [FUELQ1, FUELQ2, FUELQ3]
    weights: [0.5, 0.3, 0.2]
    rate_gph: 9.0
